#Ability Score Modifiers
Modifier.create(ability: "strength", offset: 1) #id: 1
Modifier.create(ability: "strength", offset: 2) #id: 2
Modifier.create(ability: "dexterity", offset: 1) #id: 3
Modifier.create(ability: "dexterity", offset: 2) #id: 4
Modifier.create(ability: "constitution", offset: 1) #id: 5
Modifier.create(ability: "constitution", offset: 2) #id: 6
Modifier.create(ability: "intelligence", offset: 1) #id: 7
Modifier.create(ability: "intelligence", offset: 2) #id: 8
Modifier.create(ability: "wisdom", offset: 1) #id: 9
Modifier.create(ability: "wisdom", offset: 2) #id: 10
Modifier.create(ability: "charisma", offset: 1) #id: 11
Modifier.create(ability: "charisma", offset: 2) #id: 12


# RACES (and subraces)

# Dwarf Traits

Feature.create(classifiable_id: 1, classifiable_type: "Race", name: "Darkvision", description: "Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can't discern color in darkness, only shades of gray.", level_requirement: 0)
Feature.create(classifiable_id: 1, classifiable_type: "Race", modifier_id: 6, name: "Ability Score Increase", description: "Your Constitution score increases by 2.", level_requirement: 0)
Feature.create(classifiable_id: 1, classifiable_type: "Race", name: "Dwarven Resilience", description: "You have advantage on saving throws against poison, and you have resistance against poison damage.", level_requirement: 0)
Feature.create(classifiable_id: 1, classifiable_type: "Race", name: "Dwarven Combat Training", description: "You have proficiency with the battleaxe, handaxe, light hammer, and warhammer.", level_requirement: 0)
Feature.create(classifiable_id: 1, classifiable_type: "Race", name: "Tool Proficiency", description: "You gain proficiency with the artisan’s tools of your choice: smith’s tools, brewer’s supplies, or mason’s tools.", level_requirement: 0)
Feature.create(classifiable_id: 1, classifiable_type: "Race", name: "Stonecunning", description: "Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus.", level_requirement: 0)
Feature.create(classifiable_id: 1, classifiable_type: "Race", name: "Stonecunning", description: "Whenever you make an Intelligence (History) check related to the origin of stonework, you are considered proficient in the History skill and add double your proficiency bonus to the check, instead of your normal proficiency bonus.", level_requirement: 0)

# Hill Dwarf Traits
Feature.create(classifiable_id: 1, classifiable_type: "Subrace", modifier_id: 9, name: "Ability Score Increase", description: "Your Wisdom score increases by 1.", level_requirement: 0)
Modifier.create(ability: "hit_points", offset: 1) #id: 13
Feature.create(classifiable_id: 1, classifiable_type: "Subrace", modifier_id: 13, name: "Dwarven Toughness", description: "Your hit point maximum increases by 1, and it increases by 1 every time you gain a level.", level_requirement: 0)
#Mountain Dwarf Traits
Feature.create(classifiable_id: 2, classifiable_type: "Subrace", modifier_id: 2, name: "Ability Score Increase", description: "Your Strength score increases by 2.")
Feature.create(classifiable_id: 2, classifiable_type: "Subrace", name: "Dwarven Armor Training", description: "You have proficiency with light and medium armor.")

#Elf Traits

Feature.create(classifiable_id: 2, classifiable_type: "Race", modifier_id: 4, name: "Ability Score Increase", description: "Your Dexterity score increases by 2.", level_requirement: 0)
Feature.create(classifiable_id: 2, classifiable_type: "Race", name: "Darkvision", description: "Accustomed to twilit forests and the night sky, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.", level_requirement: 0)
Feature.create(classifiable_id: 2, classifiable_type: "Race", name: "Keen Senses", description: "You have proficiency in the Perception skill.", level_requirement: 0)
Feature.create(classifiable_id: 2, classifiable_type: "Race", name: "Fey Ancestry", description: "You have advantage on saving throws against being charmed, and magic can’t put you to sleep.", level_requirement: 0)
Feature.create(classifiable_id: 2, classifiable_type: "Race", name: "Trance", description: "Elves don’t need to sleep. Instead, they meditate deeply, remaining semiconscious, for 4 hours a day. (The Common word for such meditation is “trance.”) While meditating, you can dream after a fashion; such dreams are actually mental exercises that have become reflexive through years of practice. After resting in this way, you gain the same benefit that a human does from 8 hours of sleep.", level_requirement: 0)

#High Elf Traits
Feature.create(classifiable_id: 3, classifiable_type: "Subrace", modifier_id: 7, name: "Ability Score Increase", description: "Your Intelligence score increases by 1.", level_requirement: 0)
Feature.create(classifiable_id: 3, classifiable_type: "Subrace", name: "Elf Weapon Training", description: "You have proficiency with the longsword, shortsword, shortbow, and longbow.", level_requirement: 0)
Feature.create(classifiable_id: 3, classifiable_type: "Subrace", name: "Cantrip", description: "You know one cantrip of your choice from the wizard spell list. Intelligence is your spellcasting ability for it.", level_requirement: 0)
Feature.create(classifiable_id: 3, classifiable_type: "Subrace", name: "Extra Language", description: "You can speak, read, and write one extra language of your choice.", level_requirement: 0)
#Wood Elf Traits
Feature.create(classifiable_id: 4, classifiable_type: "Subrace", modifier_id: 9, name: "Ability Score Increase", description: "Your Wisdom score increases by 1.", level_requirement: 0)
Feature.create(classifiable_id: 4, classifiable_type: "Subrace", name: "Elf Weapon Training", description: "You have proficiency with the longsword, shortsword, shortbow, and longbow.", level_requirement: 0)
Feature.create(classifiable_id: 4, classifiable_type: "Subrace", name: "Fleet of Foot", description: "Your base walking speed increases to 35 feet.", level_requirement: 0)
Feature.create(classifiable_id: 4, classifiable_type: "Subrace", name: "Mask of the Wild", description: "You can attempt to hide even when you are only lightly obscured by foliage, heavy rain, falling snow, mist, and other natural phenomena.", level_requirement: 0)
#Dark Elf Traits
Feature.create(classifiable_id: 5, classifiable_type: "Subrace", modifier_id: 11, name: "Ability Score Increase", description: "Your Charisma score increases by 1.", level_requirement: 0)
Feature.create(classifiable_id: 5, classifiable_type: "Subrace", name: "Superior Darkvision", description: "Your darkvision has a radius of 120 feet.", level_requirement: 0)
Feature.create(classifiable_id: 5, classifiable_type: "Subrace", name: "Sunlight Sensitivity", description: "You have disadvantage on attack rolls and on Wisdom (Perception) checks that rely on sight when you, the target of your attack, or whatever you are trying to perceive is in direct sunlight.", level_requirement: 0)
Feature.create(classifiable_id: 5, classifiable_type: "Subrace", name: "Drow Magic", description: "You know the dancing lights cantrip. When you reach 3rd level, you can cast the faerie fire spell once per day. When you reach 5th level, you can also cast the darkness spell once per day. Charisma is your spellcasting ability for these spells.", level_requirement: 0)
Feature.create(classifiable_id: 5, classifiable_type: "Subrace", name: "Drow Weapon Training", description: "You have proficiency with rapiers, shortswords, and hand crossbows.", level_requirement: 0)


# Halfling Traits

Feature.create(classifiable_id: 3, classifiable_type: "Race", modifier_id: 4, name: "Ability Score Increase", description: "Your Dexterity score increases by 2.", level_requirement: 0)
Feature.create(classifiable_id: 3, classifiable_type: "Race", name: "Lucky", description: "When you roll a 1 on the d20 for an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll.", level_requirement: 0)
Feature.create(classifiable_id: 3, classifiable_type: "Race", name: "Brave", description: "You have advantage on saving throws against being frightened.", level_requirement: 0)
Feature.create(classifiable_id: 3, classifiable_type: "Race", name: "Halfling Nimbleness", description: "You can move through the space of any creature that is of a size larger than yours.", level_requirement: 0)

#Lightfoot Traits
Feature.create(classifiable_id: 6, classifiable_type: "Subrace", modifier_id: 11, name: "Ability Score Increase", description: "Your Charisma score increases by 1.", level_requirement: 0)
Feature.create(classifiable_id: 6, classifiable_type: "Subrace", name: "Naturally Stealthy", description: "You can attempt to hide even when you are obscured only by a creature that is at least one size larger than you.", level_requirement: 0)
#Stout Traits
Feature.create(classifiable_id: 7, classifiable_type: "Subrace", modifier_id: 5, name: "Ability Score Increase", description: "Your Constitution score increases by 1.", level_requirement: 0)
Feature.create(classifiable_id: 7, classifiable_type: "Subrace", name: "Stout Resilience", description: "You have advanctage on saving throws against poiso, and you have resistance against poison damage.", level_requirement: 0)


# Human Traits
Feature.create(classifiable_id: 4, classifiable_type: "Race", modifier_id: 1, name: "Ability Score Increase", description: "Your ability scores each increase by 1.", level_requirement: 0)
Feature.create(classifiable_id: 4, classifiable_type: "Race", modifier_id: 3, name: "Ability Score Increase", description: "Your ability scores each increase by 1.", level_requirement: 0)
Feature.create(classifiable_id: 4, classifiable_type: "Race", modifier_id: 5, name: "Ability Score Increase", description: "Your ability scores each increase by 1.", level_requirement: 0)
Feature.create(classifiable_id: 4, classifiable_type: "Race", modifier_id: 7, name: "Ability Score Increase", description: "Your ability scores each increase by 1.", level_requirement: 0)
Feature.create(classifiable_id: 4, classifiable_type: "Race", modifier_id: 9, name: "Ability Score Increase", description: "Your ability scores each increase by 1.", level_requirement: 0)
Feature.create(classifiable_id: 4, classifiable_type: "Race", modifier_id: 11, name: "Ability Score Increase", description: "Your ability scores each increase by 1.", level_requirement: 0)


# Dragonborn Traits

Feature.create(classifiable_id: 5, classifiable_type: "Race", modifier_id: 2, name: "Ability Score Increase", description: "Your Strength score increases by 2...", level_requirement: 0)
Feature.create(classifiable_id: 5, classifiable_type: "Race", modifier_id: 2, name: "Ability Score Increase", description: "...and your Charisma score increases by 1.", level_requirement: 0)
Feature.create(classifiable_id: 5, classifiable_type: "Race", name: "Draconic Ancestry", description: "You have draconic ancestry. Choose one type of dragon from the Draconic Ancestry table. Your breath weapon and damage resistance are determined by the dragon type.", level_requirement: 0)
Feature.create(classifiable_id: 5, classifiable_type: "Race", name: "Breath Weapon", description: "You can use your action to exhale destructive energy. Your draconic ancestry determines the size, shape, and damage type of the exhalation. When you use your breath weapon, each creature in the area of the exhalation must make a saving throw, the type of which is determined by your draconic ancestry. The DC for this saving throw equals 8 + your Constitution modifier + your proficiency bonus. A creature takes 2d6 damage on a failed save, and half as much damage on a successful one. The damage increases to 3d6 at 6th level, 4d6 at 11th level, and 5d6 at 16th level. After you use your breath weapon, you can’t use it again until you complete a short or long rest.", level_requirement: 0)
Feature.create(classifiable_id: 5, classifiable_type: "Race" name: "Damage Resistance", description: "You have resistance to the damage type associated with your draconic ancestry.", level_requirement: 0)


# Gnome Traits

Feature.create(classifiable_id: 6, classifiable_type: "Race", modifier_id: 8, name: "Ability Score Increase", description: "Your Intelligence score increases by 2.", level_requirement: 0)
Feature.create(classifiable_id: 6, classifiable_type: "Race", name: "Darkvision", description: "Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.", level_requirement: 0)
Feature.create(classifiable_id: 6, classifiable_type: "Race", name: "Gnome Cunning", description: "You have advantage on all Intelligence, Wisdom, and Charisma saving throws against magic.", level_requirement: 0)

#Forest Gnome Traits
Feature.create(classifiable_id: 8, classifiable_type: "Subrace", modifier_id: 3, name: "Ability Score Increase", description: "Your Dexterity score increases by 1.", level_requirement: 0)
Feature.create(classifiable_id: 8, classifiable_type: "Subrace", name: "Natural Illusionist", description: "You know the minor illusion cantrip. Intelligence is your spellcasting ability for it.", level_requirement: 0)
Feature.create(classifiable_id: 8, classifiable_type: "Subrace", name: "Speak with Small Beasts", description: "Through sounds and gestures, you can communicate simple ideas with Small or smallers beasts. Forest gnomes love animals and often keep squirrels, badgers, rabbits, moles, woodpeckers, and other creatures as beloved pets.", level_requirement: 0)
#Rock Gnome Traits
Feature.create(classifiable_id: 9, classifiable_type: "Subrace", modifier_id: 5, name: "Ability Score Increase", description: "Your Constitution score increases by 1." level_requirement: 0)
Feature.create(classifiable_id: 9, classifiable_type: "Subrace", name: "Artificer's Lore", description: "Whenever you make an Intelligence (History) check related to magic items, alchemical objects, or technological devices, you can add twice your proficiency bonus, instead of any proficiency bonus you normally apply." level_requirement: 0)
Feature.create(classifiable_id: 9, classifiable_type: "Subrace", name: "Tinker", description: "You have proficiency with artisan’s tools (tinker’s tools). Using those tools, you can spend 1 hour and 10 gp worth of materials to construct a Tiny clockwork device (AC 5, 1 hp). The device ceases to function after 24 hours (unless you spend 1 hour repairing it to keep the device functioning), or when you use your action to dismantle it; at that time, you can reclaim the materials used to create it. You can have up to three such devices active at a time." level_requirement: 0)


# Half-Elf Traits
Feature.create(classifiable_id: 7, classifiable_type: "Race", modifier_id: 12, name: "Ability Score Increase", description: "Your Charisma score increases by 2", level_requirement: 0)
Feature.create(classifiable_id: 7, classifiable_type: "Race", name: "Ability Score Increase", description: "Two other ability scores of your choice increase by 1", level_requirement: 0) #Gonna need to make some controller actions for this, I think
Feature.create(classifiable_id: 7, classifiable_type: "Race", name: "Darkvision", description: "Thanks to your elf blood, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.", level_requirement: 0)
Feature.create(classifiable_id: 7, classifiable_type: "Race", name: "Fey Ancestry", description: "You have advantage on saving throws against being charmed, and magic can’t put you to sleep.", level_requirement: 0)
Feature.create(classifiable_id: 7, classifiable_type: "Race", name: "Skill Versatility", description: "You gain proficiency in two skills of your choice.", level_requirement: 0) #FUCK I NEED TO HARDCODE SO MUCH STUFF FOR HALF-ELVES


# Half-Orc Traits
Feature.create(classifiable_id: 8, classifiable_type: "Race", modifier_id: 2, name: "Ability Score Increase", description: "Your Strength score increases by 2...", level_requirement: 0)
Feature.create(classifiable_id: 8, classifiable_type: "Race", modifier_id: 5, name: "Ability Score Increase", description: "...and your Constitution score increases by 1.", level_requirement: 0)
Feature.create(classifiable_id: 8, classifiable_type: "Race", name: "Darkvision", description: "Thanks to your orc blood, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.", level_requirement: 0)
Feature.create(classifiable_id: 8, classifiable_type: "Race", name: "Menacing", description: "You gain proficiency in the Intimidation skill.", level_requirement: 0) #Have to hard code this too...
Feature.create(classifiable_id: 8, classifiable_type: "Race", name: "Relentless Endurance", description: "When you are reduced to 0 hit points but not killed outright, you can drop to 1 hit point instead. You can’t use this feature again until you finish a long rest.", level_requirement: 0)
Feature.create(classifiable_id: 8, classifiable_type: "Race", name: "Savage Attacks", description: "When you score a critical hit with a melee weapon attack, you can roll one of the weapon’s damage dice one additional time and add it to the extra damage of the critical hit.", level_requirement: 0)


# Tiefling Traits
Feature.create(classifiable_id: 9, classifiable_type: "Race", modifier_id: 7, name: "Ability Score Increase", description: "Your Intelligence score increases by 1...", level_requirement: 0)
Feature.create(classifiable_id: 9, classifiable_type: "Race", modifier_id: 12, name: "Ability Score Increase", description: "...and your Charisma score increases by 2", level_requirement: 0)
Feature.create(classifiable_id: 9, classifiable_type: "Race", name: "Darkvision", description: "Thanks to your infernal heritage, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can’t discern color in darkness, only shades of gray.", level_requirement: 0)
Feature.create(classifiable_id: 9, classifiable_type: "Race", name: "Hellish Resistance", description: "You have resistance to fire damage.", level_requirement: 0)
Feature.create(classifiable_id: 9, classifiable_type: "Race", name: "Infernal Legacy", description: "You know the thaumaturgy cantrip. When you reach 3rd level, you can cast the hellish rebuke spell as a 2nd-level spell once with this trait and regain the ability to do so when you finish a long rest. When you reach 5th level, you can cast the darkness spell once with this trait and regain the ability to do so when you finish a long rest. Charisma is your spellcasting ability for these spells.", level_requirement: 0)



# CLASSES

# Barbarian Features

Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Armor Proficiencies", description: "Light armor, medium armor, shields", level_requirement: 1)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Simple weapons, martial weapons", level_requirement: 1)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Rage", description: "In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action. While raging, you gain the following benefits if you aren’t wearing heavy armor: 
You have advantage on Strength checks and Strength saving throws.
When you make a melee weapon attack using Strength, you gain a bonus to the damage roll that increases as you gain levels as a barbarian, as shown in the Rage Damage column of the Barbarian table.
You have resistance to bludgeoning, piercing, and slashing damage.
If you are able to cast spells, you can’t cast them or concentrate on them while raging.
Your rage lasts for 1 minute. It ends early if you are knocked unconscious or if your turn ends and you haven’t attacked a hostile creature since your last turn or taken damage since then. You can also end your rage on your turn as a bonus action. Once you have raged the number of times shown for your barbarian level in the Rages column of the Barbarian table, you must finish a long rest before you can rage again.", level_requirement: 1)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Unarmored Defense", description: "While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit.", level_requirement: 1)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Reckless Attack", description: "Starting at 2nd level, you can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly. Doing so gives you advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn.", level_requirement: 2)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Danger Sense", description: "At 2nd level, you gain an uncanny sense of when things nearby aren’t as they should be, giving you an edge when you dodge away from danger. You have advantage on Dexterity saving throws against effects that you can see, such as traps and spells. To gain this benefit, you can’t be blinded, deafened, or incapacitated.", level_requirement: 2)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Primal Path", description: "At 3rd level, you choose a path that shapes the nature of your rage. Choose the Path of the Berserker or the Path of the Totem Warrior. Your choice grants you features at 3rd level, and again at 6th, 10th, and 14th levels.", level_requirement: 3)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Extra Attack", description: "Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.", level_requirement: 5)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Fast Movement", description: "Starting at 5th level, your speed increases by 10 feet while you aren’t wearing heavy armor.", level_requirement: 5)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Feral Instincts", description: "By 7th level, your instincts are so honed that you have advantage on initiative rolls. Additionally, if you are surprised at the beginning of combat and aren’t incapacitated, you can act normally on your first turn, but only if you enter your rage before doing anything else on that turn.", level_requirement: 7)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Brutal Critical", description: "Beginning at 9th level, you can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack. This increases to two additional dice at 13th level and three additional dice at 17th level.", level_requirement: 9)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Relentless Rage", description: "Starting at 11th level, your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while you’re raging and don’t die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead. Each time you use this feature after the first, the DC increases by 5. When you finish a short or long rest, the DC resets to 10.", level_requirement: 11)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Persistent Rage", description: "Beginning at 15th level, your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it.", level_requirement: 15)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Indomitable Might", description: "Beginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total.", level_requirement: 18)
Feature.create(classifiable_id: 1, classifiable_type: "Klass", name: "Primal Champion", description: "At 20th level, you embody the power of the wilds. Your Strength and Constitution scores increase by 4. Your maximum for those scores is now 24.", level_requirement: 20)


# Bard Features

Feaure.create(classifiable_id: 2, classifiable_type: "Klass", name: "Armor Proficiencies", description: "Light armor", level_requirement: 1)
Feaure.create(classifiable_id: 2, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Simple weapons, hand crossbows, longswords, rapiers, shortswords", level_requirement: 1)
Feaure.create(classifiable_id: 2, classifiable_type: "Klass", name: "Tool Proficiencies", description: "Three musical instruments of your choice", level_requirement: 1)
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Spellcasting", description: "You have learned to untangle and reshape the fabric of reality in harmony with your wishes and music. Your spells are part of your vast repertoire, magic that you can tune to different situations.", level_requirement: 1)
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Bardic Inspiration", description: "You can inspire others through stirring words or music. To do so, you use a bonus action on your turn to choose one creature other than yourself within 60 feet of you who can hear you. That creature gains one Bardic Inspiration die, a d6. Once within the next 10 minutes, the creature can roll the die and add the number rolled to one ability check, attack roll, or saving throw it makes. The creature can wait until after it rolls the d20 before deciding to use the Bardic Inspiration die, but must decide before the GM says whether the roll succeeds or fails. Once the Bardic Inspiration die is rolled, it is lost. A creature can have only one Bardic Inspiration die at a time. You can use this feature a number of times equal to your Charisma modifier (a minimum of once). You regain any expended uses when you finish a long rest. Your Bardic Inspiration die changes when you reach certain levels in this class. The die becomes a d8 at 5th level, a d10 at 10th level, and a d12 at 15th level.", level_requirement: 1)
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Jack of All Trades", description: "Starting at 2nd level, you can add half your proficiency bonus, rounded down, to any ability check you make that doesn’t already include your proficiency bonus.", level_requirement: 2) #Yeah gonna have to code this one in.
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Song of Rest", description: "Beginning at 2nd level, you can use soothing music or oration to help revitalize your wounded allies during a short rest. If you or any friendly creatures who can hear your performance regain hit points at the end of the short rest by spending one or more Hit Dice, each of those creatures regains an extra 1d6 hit points. The extra hit points increase when you reach certain levels in this class: to 1d8 at 9th level, to 1d10 at 13th level, and to 1d12 at 17th level.", level_requirement: 2)
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Bard College", description: "At 3rd level, you delve into the advanced techniques of a Bardic College. Your choice grants you features at 3rd level and again at 6th and 14th level.", level_requirement: 3)
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Expertise", description: "At 3rd level, choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies. At 10th level, you can choose another two skill proficiencies to gain this benefit.", level_requirement: 3) # >:[
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Font of Inspiration", description: "Beginning when you reach 5th level, you regain all of your expended uses of Bardic Inspiration when you finish a short or long rest.", level_requirement: 5)
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Countercharm", description: "At 6th level, you gain the ability to use musical notes or words of power to disrupt mind-influencing effects. As an action, you can start a performance that lasts until the end of your next turn. During that time, you and any friendly creatures within 30 feet of you have advantage on saving throws against being frightened or charmed. A creature must be able to hear you to gain this benefit. The performance ends early if you are incapacitated or silenced or if you voluntarily end it (no action required).", level_requirement: 6)
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Magical Secrets", description: "By 10th level, you have plundered magical knowledge from a wide spectrum of disciplines. Choose two spells from any class, including this one. A spell you choose must be of a level you can cast, as shown on the Bard table, or a cantrip. The chosen spells count as bard spells for you and are included in the number in the Spells Known column of the Bard table. You learn two additional spells from any class at 14th level and again at 18th level.", level_requirement: 10)
Feature.create(classifiable_id: 2, classifiable_type: "Klass", name: "Superior Inspiration", description: "At 20th level, when you roll initiative and have no uses of Bardic Inspiration left, you regain one use.", level_requirement: 10)


# Cleric Features

Feature.create(classifiable_id: 3, classifiable_type: "Klass", name: "Armor Proficiencies", description: "Light armor, medium armor, shields", level_requirement: 1)
Feature.create(classifiable_id: 3, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Simple weapons", level_requirement: 1)
Feature.create(classifiable_id: 3, classifiable_type: "Klass", name: "Spellcasting", description: "As a conduit for divine power, you can cast cleric spells.", level_requirement: 1)
Feature.create(classifiable_id: 3, classifiable_type: "Klass", name: "Divine Domain", description: "Choose one domain related to your deity. Your chosen domain grants you domain spells and other features when you choose it at 1st level. It also grants you additional ways to use Channel Divinity when you gain that feature at 2nd level, and additional benefits at 6th, 8th, and 17th levels.", level_requirement: 1)
Feature.create(classifiable_id: 3, classifiable_type: "Klass", name: "Channel Divinity", description: "At 2nd level, you gain the ability to channel divine energy directly from your deity, using that energy to fuel magical effects. You start with two such effects: Turn Undead and an effect determined by your domain. Some domains grant you additional effects as you advance in levels, as noted in the domain description. When you use your Channel Divinity, you choose which effect to create. You must then finish a short or long rest to use your Channel Divinity again. Some Channel Divinity effects require saving throws. When you use such an effect from this class, the DC equals your cleric spell save DC. Beginning at 6th level, you can use your Channel Divinity twice between rests, and beginning at 18th level, you can use it three times between rests. When you finish a short or long rest, you regain your expended uses.", level_requirement: 2)
Feature.create(classifiable_id: 3, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 3, classifiable_type: "Klass", name: "Destroy Undead", description: "Starting at 5th level, when an undead fails its saving throw against your Turn Undead feature, the creature is instantly destroyed if its challenge rating is at or below a certain threshold, as shown in the Destroy Undead table.", level_requirement: 5)
Feature.create(classifiable_id: 3, classifiable_type: "Klass", name: "Divine Intervention", description: "Beginning at 10th level, you can call on your deity to intervene on your behalf when your need is great. Imploring your deity’s aid requires you to use your action. Describe the assistance you seek, and roll percentile dice. If you roll a number equal to or lower than your cleric level, your deity intervenes. The GM chooses the nature of the intervention; the effect of any cleric spell or cleric domain spell would be appropriate. If your deity intervenes, you can’t use this feature again for 7 days. Otherwise, you can use it again after you finish a long rest. At 20th level, your call for intervention succeeds automatically, no roll required.", level_requirement: 10)



# Druid Features

Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Armor Proficiencies", description: "Light armor, medium armor, shields (druids will not wear armor or use shields made of metal", level_requirement: 1)
Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Clubs, daggers, darts, javelins, maces, quarterstaffs, scimitars, sickles, slings, spears", level_requirement: 1)
Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Tool Proficiencies", description: "Herbalism kit", level_requirement: 1)
Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Spellcasting", description: "Drawing on the divine essence of nature itself, you can cast spells to shape that essence to your will.", level_requirement: 1)
Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Wild Shape", description: "Starting at 2nd level, you can use your action to magically assume the shape of a beast that you have seen before. You can use this feature twice. You regain expended uses when you finish a short or long rest. Your druid level determines the beasts you can transform into, as shown in Table: Beast Shapes. At 2nd level, for example, you can transform into any beast that has a challenge rating of 1/4 or lower that doesn’t have a flying or swimming speed.You can stay in a beast shape for a number of hours equal to half your druid level (rounded down). You then revert to your normal form unless you expend another use of this feature. You can revert to your normal form earlier by using a bonus action on your turn. You automatically revert if you fall unconscious, drop to 0 hit points, or die.
While you are transformed, the following rules apply:
Your game statistics are replaced by the statistics of the beast, but you retain your alignment, personality, and Intelligence, Wisdom, and Charisma scores. You also retain all of your skill and saving throw proficiencies, in addition to gaining those of the creature. If the creature has the same proficiency as you and the bonus in its stat block is higher than yours, use the creature’s bonus instead of yours. If the creature has any legendary or lair actions, you can’t use them.
When you transform, you assume the beast’s hit points and Hit Dice. When you revert to your normal form, you return to the number of hit points you had before you transformed. However, if you revert as a result of dropping to 0 hit points, any excess damage carries over to your normal form. For example, if you take 10 damage in animal form and have only 1 hit point left, you revert and take 9 damage. As long as the excess damage doesn’t reduce your normal form to 0 hit points, you aren’t knocked unconscious.
You can’t cast spells, and your ability to speak or take any action that requires hands is limited to the capabilities of your beast form. Transforming doesn’t break your concentration on a spell you’ve already cast, however, or prevent you from taking actions that are part of a spell, such as call lightning, that you’ve already cast.
You retain the benefit of any features from your class, race, or other source and can use them if the new form is physically capable of doing so. However, you can’t use any of your special senses, such as darkvision, unless your new form also has that sense.
You choose whether your equipment falls to the ground in your space, merges into your new form, or is worn by it. Worn equipment functions as normal, but the GM decides whether it is practical for the new form to wear a piece of equipment, based on the creature’s shape and size. Your equipment doesn’t change size or shape to match the new form, and any equipment that the new form can’t wear must either fall to the ground or merge with it. Equipment that merges with the form has no effect until you leave the form.", level_requirement: 2)
Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Druid Circle", description: "At 2nd level, you choose to identify with a circle of druids. Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level.", level_requirement: 2)
Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Timeless Body", description: "Starting at 18th level, the primal magic that you wield causes you to age more slowly. For every 10 years that pass, your body ages only 1 year.", level_requirement: 18)
Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Beast Spells", description: "Beginning at 18th level, you can cast many of your druid spells in any shape you assume using Wild Shape. You can perform the somatic and verbal components of a druid spell while in a beast shape, but you aren’t able to provide material components.", level_requirement: 18)
Feature.create(classifiable_id: 4, classifiable_type: "Klass", name: "Archdruid", description: "At 20th level, you can use your Wild Shape an unlimited number of times. Additionally, you can ignore the verbal and somatic components of your druid spells, as well as any material components that lack a cost and aren’t consumed by a spell. You gain this benefit in both your normal shape and your beast shape from Wild Shape.", level_requirement: 20)


# Fighter Features

Feature.create(classifiable_id: 5, classifiable_type: "Klass", name: "Armor Proficiencies", description: "All armor, shields", level_requirement: 1)
Feature.create(classifiable_id: 5, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Simple weapons, Martial weapons", level_requirement: 1)
Feature.create(classifiable_id: 5, classifiable_type: "Klass", name: "Fighting Style", description: "You adopt a particular style of fighting as your specialty. Choose one of the following options. You can’t take a Fighting Style option more than once, even if you later get to choose again.
Archery
You gain a +2 bonus to attack rolls you make with ranged weapons.
Defense
While you are wearing armor, you gain a +1 bonus to AC.
Dueling
When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.
Great Weapon Fighting
When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll, even if the new roll is a 1 or a 2. The weapon must have the two-handed or versatile property for you to gain this benefit.
Protection
When a creature you can see attacks a target other than you that is within 5 feet of you, you can use your reaction to impose disadvantage on the attack roll. You must be wielding a shield.
Two-Weapon Fighting
When you engage in two-weapon fighting, you can add your ability modifier to the damage of the second attack.", level_requirement: 1)
Feature.create(classifiable_id: 5, classifiable_type: "Klass", name: "Second Wind", description: "You have a limited well of stamina that you can draw on to protect yourself from harm. On your turn, you can use a bonus action to regain hit points equal to 1d10 + your fighter level. Once you use this feature, you must finish a short or long rest before you can use it again.", level_requirement: 1)
Feature.create(classifiable_id: 5, classifiable_type: "Klass", name: "Action Surge", description: "Starting at 2nd level, you can push yourself beyond your normal limits for a moment. On your turn, you can take one additional action on top of your regular action and a possible bonus action. Once you use this feature, you must finish a short or long rest before you can use it again. Starting at 17th level, you can use it twice before a rest, but only once on the same turn.", level_requirement: 2)
Feature.create(classifiable_id: 5, classifiable_type: "Klass", name: "Martial Archetype", description: "At 3rd level, you choose an archetype that you strive to emulate in your combat styles and techniques.", level_requirement: 3)
Feature.create(classifiable_id: 5, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 6th, 8th, 12th, 14th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 5, classifiable_type: "Klass", name: "Extra Attack", description: "Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn. The number of attacks increases to three when you reach 11th level in this class and to four when you reach 20th level in this class.", level_requirement: 5)
Feature.create(classifiable_id: 5, classifiable_type: "Klass", name: "Indomitable", description: "Beginning at 9th level, you can reroll a saving throw that you fail. If you do so, you must use the new roll, and you can’t use this feature again until you finish a long rest. You can use this feature twice between long rests starting at 13th level and three times between long rests starting at 17th level.", level_requirement: 9)


# Monk Features

Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Simple weapons, shortswords", level_requirement: 1)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Tool Proficiencies", description: "Choose one type of artisan's tools or one musical instrument", level_requirement: 1)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Unarmored Defense", description: "Beginning at 1st level, while you are wearing no armor and not wielding a shield, your AC equals 10 + your Dexterity modifier + your Wisdom modifier.", level_requirement: 1)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Martial Arts", description: "At 1st level, your practice of martial arts gives you mastery of combat styles that use unarmed strikes and monk weapons, which are shortswords and any simple melee weapons that don’t have the two- handed or heavy property.
You gain the following benefits while you are unarmed or wielding only monk weapons and you aren’t wearing armor or wielding a shield:
You can use Dexterity instead of Strength for the attack and damage rolls of your unarmed strikes and monk weapons.
You can roll a d4 in place of the normal damage of your unarmed strike or monk weapon. This die changes as you gain monk levels, as shown in the Martial Arts column of Table: The Monk.
When you use the Attack action with an unarmed strike or a monk weapon on your turn, you can make one unarmed strike as a bonus action. For example, if you take the Attack action and attack with a quarterstaff, you can also make an unarmed strike as a bonus action, assuming you haven’t already taken a bonus action this turn.
Certain monasteries use specialized forms of the monk weapons. For example, you might use a club that is two lengths of wood connected by a short chain (called a nunchaku) or a sickle with a shorter, straighter blade (called a kama). Whatever name you use for a monk weapon, you can use the game statistics provided for the weapon.", level_requirement: 1)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Ki", description: "Starting at 2nd level, your training allows you to harness the mystic energy of ki. Your access to this energy is represented by a number of ki points. Your monk level determines the number of points you have, as shown in the Ki Points column of Table: The Monk. You can spend these points to fuel various ki features. You start knowing three such features: Flurry of Blows, Patient Defense, and Step of the Wind. You learn more ki features as you gain levels in this class. When you spend a ki point, it is unavailable until you finish a short or long rest, at the end of which you draw all of your expended ki back into yourself. You must spend at least 30 minutes of the rest meditating to regain your ki points. Some of your ki features require your target to make a saving throw to resist the feature’s effects. The saving throw DC is calculated as follows:
Ki save DC = 8 + your proficiency bonus + your Wisdom modifier
Flurry of Blows
Immediately after you take the Attack action on your turn, you can spend 1 ki point to make two unarmed strikes as a bonus action.
Patient Defense
You can spend 1 ki point to take the Dodge action as a bonus action on your turn.
Step of the Wind
You can spend 1 ki point to take the Disengage or Dash action as a bonus action on your turn, and your jump distance is doubled for the turn.", level_requirement: 2)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Unarmored Movement", description: "Starting at 2nd level, your speed increases by 10 feet while you are not wearing armor or wielding a shield. This bonus increases when you reach certain monk levels, as shown in Table: The Monk.
At 9th level, you gain the ability to move along vertical surfaces and across liquids on your turn without falling during the move.", level_requirement: 2)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Monastic Tradition", description: "When you reach 3rd level, you commit yourself to a monastic tradition. Your tradition grants you features at 3rd level and again at 6th, 11th, and 17th level.", level_requirement: 3)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Deflect Missiles", description: "Starting at 3rd level, you can use your reaction to deflect or catch the missile when you are hit by a ranged weapon attack. When you do so, the damage you take from the attack is reduced by 1d10 + your Dexterity modifier + your monk level. If you reduce the damage to 0, you can catch the missile if it is small enough for you to hold in one hand and you have at least one hand free. If you catch a missile in this way, you can spend 1 ki point to make a ranged attack with the weapon or piece of ammunition you just caught, as part of the same reaction. You make this attack with proficiency, regardless of your weapon proficiencies, and the missile counts as a monk weapon for the attack, which has a normal range of 20 feet and a long range of 60 feet.", level_requirement: 3)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Slow Fall", description: "Beginning at 4th level, you can use your reaction when you fall to reduce any falling damage you take by an amount equal to five times your monk level.", level_requirement: 4)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Extra Attack", description: "Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.", level_requirement: 5)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Stunning Strike", description: "Starting at 5th level, you can interfere with the flow of ki in an opponent’s body. When you hit another creature with a melee weapon attack, you can spend 1 ki point to attempt a stunning strike. The target must succeed on a Constitution saving throw or be stunned until the end of your next turn.", level_requirement: 5)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Ki-Empowered Strikes", description: "Starting at 6th level, your unarmed strikes count as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage.", level_requirement: 6)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Evasion", description: "At 7th level, your instinctive agility lets you dodge out of the way of certain area effects, such as a blue dragon’s lightning breath or a fireball spell. When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail.", level_requirement: 7)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Stillness of Mind", description: "Starting at 7th level, you can use your action to end one effect on yourself that is causing you to be charmed or frightened.", level_requirement: 7)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Purity of Body", description: "At 10th level, your mastery of the ki flowing through you makes you immune to disease and poison.", level_requirement: 10)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Tongue of the Sun and Moon", description: "Starting at 13th level, you learn to touch the ki of other minds so that you understand all spoken languages. Moreover, any creature that can understand a language can understand what you say.", level_requirement: 13)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Diamond Soul", description: "Beginning at 14th level, your mastery of ki grants you proficiency in all saving throws. Additionally, whenever you make a saving throw and fail, you can spend 1 ki point to reroll it and take the second result.", level_requirement: 14)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Timeless Body", description: "At 15th level, your ki sustains you so that you suffer none of the frailty of old age, and you can’t be aged magically. You can still die of old age, however. In addition, you no longer need food or water.", level_requirement: 15)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Empty Body", description: "Beginning at 18th level, you can use your action to spend 4 ki points to become invisible for 1 minute. During that time, you also have resistance to all damage but force damage. Additionally, you can spend 8 ki points to cast the astral projection spell, without needing material components. When you do so, you can’t take any other creatures with you.", level_requirement: 18)
Feature.create(classifiable_id: 6, classifiable_type: "Klass", name: "Perfect Self", description: "At 20th level, when you roll for initiative and have no ki points remaining, you regain 4 ki points.", level_requirement: 20)


# Paladin Features

Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Armor Proficiencies", description: "All armor, shields", level_requirement: 1)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Simple weapons, martial weapons", level_requirement: 1)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Divine Sense", description: "The presence of strong evil registers on your senses like a noxious odor, and powerful good rings like heavenly music in your ears. As an action, you can open your awareness to detect such forces. Until the end of your next turn, you know the location of any celestial, fiend, or undead within 60 feet of you that is not behind total cover. You know the type (celestial, fiend, or undead) of any being whose presence you sense, but not its identity. Within the same radius, you also detect the presence of any place or object that has been consecrated or desecrated, as with the hallow spell. You can use this feature a number of times equal to 1 + your Charisma modifier. When you finish a long rest, you regain all expended uses.", level_requirement: 1)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Lay on Hands", description: "Your blessed touch can heal wounds. You have a pool of healing power that replenishes when you take a long rest. With that pool, you can restore a total number of hit points equal to your paladin level × 5. As an action, you can touch a creature and draw power from the pool to restore a number of hit points to that creature, up to the maximum amount remaining in your pool. Alternatively, you can expend 5 hit points from your pool of healing to cure the target of one disease or neutralize one poison affecting it. You can cure multiple diseases and neutralize multiple poisons with a single use of Lay on Hands, expending hit points separately for each one.This feature has no effect on undead and constructs.", level_requirement: 1)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Fighting Style", description: "At 2nd level, you adopt a style of fighting as your specialty. Choose one of the following options. You can’t take a Fighting Style option more than once, even if you later get to choose again.
Defense
While you are wearing armor, you gain a +1 bonus to AC.
Dueling
When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.
Great Weapon Fighting
When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll. The weapon must have the two-handed or versatile property for you to gain this benefit.
Protection
When a creature you can see attacks a target other than you that is within 5 feet of you, you can use your reaction to impose disadvantage on the attack roll. You must be wielding a shield.", level_requirement: 2)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Spellcasting", description: "By 2nd level, you have learned to draw on divine magic through meditation and prayer to cast spells as a cleric does.", level_requirement: 2)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Divine Smite", description: "Starting at 2nd level, when you hit a creature with a melee weapon attack, you can expend one spell slot to deal radiant damage to the target, in addition to the weapon’s damage. The extra damage is 2d8 for a 1st-level spell slot, plus 1d8 for each spell level higher than 1st, to a maximum of 5d8. The damage increases by 1d8 if the target is an undead or a fiend.", level_requirement: 2)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Divine Health", description: "By 3rd level, the divine magic flowing through you makes you immune to disease.", level_requirement: 3)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Sacred Oath", description: "When you reach 3rd level, you swear the oath that binds you as a paladin forever. Up to this time you have been in a preparatory stage, committed to the path but not yet sworn to it. Your choice grants you features at 3rd level and again at 7th, 15th, and 20th level. Those features include oath spells and the Channel Divinity feature.
Oath Spells
Each oath has a list of associated spells. You gain access to these spells at the levels specified in the oath description. Once you gain access to an oath spell, you always have it prepared. Oath spells don’t count against the number of spells you can prepare each day. If you gain an oath spell that doesn’t appear on the paladin spell list, the spell is nonetheless a paladin spell for you.
Channel Divinity
Your oath allows you to channel divine energy to fuel magical effects. Each Channel Divinity option provided by your oath explains how to use it. When you use your Channel Divinity, you choose which option to use. You must then finish a short or long rest to use your Channel Divinity again. Some Channel Divinity effects require saving throws. When you use such an effect from this class, the DC equals your paladin spell save DC.", level_requirement: 3)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Extra Attack", description: "Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.", level_requirement: 5)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Aura of Protection", description: "Starting at 6th level, whenever you or a friendly creature within 10 feet of you must make a saving throw, the creature gains a bonus to the saving throw equal to your Charisma modifier (with a minimum bonus of +1). You must be conscious to grant this bonus. At 18th level, the range of this aura increases to 30 feet.", level_requirement: 6)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Aura of Courage", description: "Starting at 10th level, you and friendly creatures within 10 feet of you can’t be frightened while you are conscious. At 18th level, the range of this aura increases to 30 feet.", level_requirement: 10)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Improved Divine Smite", description: "By 11th level, you are so suffused with righteous might that all your melee weapon strikes carry divine power with them. Whenever you hit a creature with a melee weapon, the creature takes an extra 1d8 radiant damage. If you also use your Divine Smite with an attack, you add this damage to the extra damage of your Divine Smite.", level_requirement: 11)
Feature.create(classifiable_id: 7, classifiable_type: "Klass", name: "Cleansing Touch", description: "Beginning at 14th level, you can use your action to end one spell on yourself or on one willing creature that you touch. You can use this feature a number of times equal to your Charisma modifier (a minimum of once). You regain expended uses when you finish a long rest.", level_requirement: 14)


# Ranger Features

Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Armor Proficiencies", description: "Light armor, medium armor, shields", level_requirement: 1)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Simple weapons, martial weapons", level_requirement: 1)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Favored Enemy", description: "Beginning at 1st level, you have significant experience studying, tracking, hunting, and even talking to a certain type of enemy.
Choose a type of favored enemy: aberrations, beasts, celestials, constructs, dragons, elementals, fey, fiends, giants, monstrosities, oozes, plants, or undead. Alternatively, you can select two races of humanoid (such as gnolls and orcs) as favored enemies. 
You have advantage on Wisdom (Survival) checks to track your favored enemies, as well as on Intelligence checks to recall information about them. When you gain this feature, you also learn one language of your choice that is spoken by your favored enemies, if they speak one at all. You choose one additional favored enemy, as well as an associated language, at 6th and 14th level. As you gain levels, your choices should reflect the types of monsters you have encountered on your adventures.", level_requirement: 1)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Natural Explorer", description: "You are particularly familiar with one type of natural environment and are adept at traveling and surviving in such regions. Choose one type of favored terrain: arctic, coast, desert, forest, grassland, mountain, or swamp. When you make an Intelligence or Wisdom check related to your favored terrain, your proficiency bonus is doubled if you are using a skill that you’re proficient in.
While traveling for an hour or more in your favored terrain, you gain the following benefits:
Difficult terrain doesn’t slow your group’s travel.
Your group can’t become lost except by magical means.
Even when you are engaged in another activity while traveling (such as foraging, navigating, or tracking), you remain alert to danger.
If you are traveling alone, you can move stealthily at a normal pace.
When you forage, you find twice as much food as you normally would.
While tracking other creatures, you also learn their exact number, their sizes, and how long ago they passed through the area.
You choose additional favored terrain types at 6th and 10th level.", level_requirement: 1)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Fighting Style", description: "At 2nd level, you adopt a particular style of fighting as your specialty. Choose one of the following options. You can’t take a Fighting Style option more than once, even if you later get to choose again.
Archery
You gain a +2 bonus to attack rolls you make with ranged weapons.
Defense
While you are wearing armor, you gain a +1 bonus to AC.
Dueling
When you are wielding a melee weapon in one hand and no other weapons, you gain a +2 bonus to damage rolls with that weapon.
Two-Weapon Fighting
When you engage in two-weapon fighting, you can add your ability modifier to the damage of the second attack.", level_requirement: 2)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Spellcasting", description: "By the time you reach 2nd level, you have learned to use the magical essence of nature to cast spells, much as a druid does.", level_requirement: 2)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Ranger Archetype", description: "At 3rd level, you choose an archetype that you strive to emulate. Your choice grants you features at 3rd level and again at 7th, 11th, and 15th level.", level_requirement: 3)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Primeval Awareness", description: "Beginning at 3rd level, you can use your action and expend one ranger spell slot to focus your awareness on the region around you. For 1 minute per level of the spell slot you expend, you can sense whether the following types of creatures are present within 1 mile of you (or within up to 6 miles if you are in your favored terrain): aberrations, celestials, dragons, elementals, fey, fiends, and undead. This feature doesn’t reveal the creatures’ location or number.", level_requirement: 3)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Extra Attack", description: "Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.", level_requirement: 5)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Land's Stride", description: "Starting at 8th level, moving through nonmagical difficult terrain costs you no extra movement. You can also pass through nonmagical plants without being slowed by them and without taking damage from them if they have thorns, spines, or a similar hazard. In addition, you have advantage on saving throws against plants that are magically created or manipulated to impede movement, such those created by the entangle spell.", level_requirement: 8)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Hide in Plain Sight", description: "Starting at 10th level, you can spend 1 minute creating camouflage for yourself. You must have access to fresh mud, dirt, plants, soot, and other naturally occurring materials with which to create your camouflage. Once you are camouflaged in this way, you can try to hide by pressing yourself up against a solid surface, such as a tree or wall, that is at least as tall and wide as you are. You gain a +10 bonus to Dexterity (Stealth) checks as long as you remain there without moving or taking actions. Once you move or take an action or a reaction, you must camouflage yourself again to gain this benefit.", level_requirement: 10)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Vanish", description: "Starting at 14th level, you can use the Hide action as a bonus action on your turn. Also, you can’t be tracked by nonmagical means, unless you choose to leave a trail.", level_requirement: 14)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Vanish", description: "At 18th level, you gain preternatural senses that help you fight creatures you can’t see. When you attack a creature you can’t see, your inability to see it doesn’t impose disadvantage on your attack rolls against it. You are also aware of the location of any invisible creature within 30 feet of you, provided that the creature isn’t hidden from you and you aren’t blinded or deafened.", level_requirement: 18)
Feature.create(classifiable_id: 8, classifiable_type: "Klass", name: "Foe Slayer", description: "At 20th level, you become an unparalleled hunter of your enemies. Once on each of your turns, you can add your Wisdom modifier to the attack roll or the damage roll of an attack you make against one of your favored enemies. You can choose to use this feature before or after the roll, but before any effects of the roll are applied.", level_requirement: 20)


# Rogue Features

Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Armor Proficiencies", description: "Light armor", level_requirement: 1)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Simple weapons, hand crossbows, longswords, rapiers, shortswords", level_requirement: 1)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Tool Proficiencies", description: "Thieves' tools", level_requirement: 1)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Expertise", description: "At 1st level, choose two of your skill proficiencies, or one of your skill proficiencies and your proficiency with thieves’ tools. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies. At 6th level, you can choose two more of your proficiencies (in skills or with thieves’ tools) to gain this benefit.", level_requirement: 1)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Sneak Attack", description: "Beginning at 1st level, you know how to strike subtly and exploit a foe’s distraction. Once per turn, you can deal an extra 1d6 damage to one creature you hit with an attack if you have advantage on the attack roll. The attack must use a finesse or a ranged weapon. You don’t need advantage on the attack roll if another enemy of the target is within 5 feet of it, that enemy isn’t incapacitated, and you don’t have disadvantage on the attack roll. The amount of the extra damage increases as you gain levels in this class, as shown in the Sneak Attack column of the Rogue table.", level_requirement: 1)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Thieves' Cant", description: "During your rogue training you learned thieves’ cant, a secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation. Only another creature that knows thieves’ cant understands such messages. It takes four times longer to convey such a message than it does to speak the same idea plainly. In addition, you understand a set of secret signs and symbols used to convey short, simple messages, such as whether an area is dangerous or the territory of a thieves’ guild, whether loot is nearby, or whether the people in an area are easy marks or will provide a safe house for thieves on the run.", level_requirement: 1)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Cunning Action", description: "Starting at 2nd level, your quick thinking and agility allow you to move and act quickly. You can take a bonus action on each of your turns in combat. This action can be used only to take the Dash, Disengage, or Hide action.", level_requirement: 2)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Roguish Archetype", description: "At 3rd level, you choose an archetype that you emulate in the exercise of your rogue abilities. Your archetype choice grants you features at 3rd level and then again at 9th, 13th, and 17th level.", level_requirement: 3)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 10th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Uncanny Dodge", description: "Starting at 5th level, when an attacker that you can see hits you with an attack, you can use your reaction to halve the attack’s damage against you.", level_requirement: 5)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Evasion", description: "Beginning at 7th level, you can nimbly dodge out of the way of certain area effects, such as a red dragon’s fiery breath or an ice storm spell. When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail.", level_requirement: 7)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Evasion", description: "Beginning at 7th level, you can nimbly dodge out of the way of certain area effects, such as a red dragon’s fiery breath or an ice storm spell. When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail.", level_requirement: 7)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Reliable Talent", description: "By 11th level, you have refined your chosen skills until they approach perfection. Whenever you make an ability check that lets you add your proficiency bonus, you can treat a d20 roll of 9 or lower as a 10.", level_requirement: 11)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Blindsense", description: "Starting at 14th level, if you are able to hear, you are aware of the location of any hidden or invisible creature within 10 feet of you.", level_requirement: 14)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Slippery Mind", description: "By 15th level, you have acquired greater mental strength. You gain proficiency in Wisdom saving throws.", level_requirement: 15)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Slippery Mind", description: "Beginning at 18th level, you are so evasive that attackers rarely gain the upper hand against you. No attack roll has advantage against you while you aren’t incapacitated.", level_requirement: 18)
Feature.create(classifiable_id: 9, classifiable_type: "Klass", name: "Stroke of Luck", description: "At 20th level, you have an uncanny knack for succeeding when you need to. If your attack misses a target within range, you can turn the miss into a hit. Alternatively, if you fail an ability check, you can treat the d20 roll as a 20. Once you use this feature, you can’t use it again until you finish a short or long rest.", level_requirement: 20)


# Sorceror Features

Feature.create(classifiable_id: 10, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Daggers, darts, slings, quarterstaffs, light crossbows", level_requirement: 1)
Feature.create(classifiable_id: 10, classifiable_type: "Klass", name: "Spellcasting", description: "An event in your past, or in the life of a parent or ancestor, left an indelible mark on you, infusing you with arcane magic. This font of magic, whatever its origin, fuels your spells.", level_requirement: 1)
Feature.create(classifiable_id: 10, classifiable_type: "Klass", name: "Sorcerous Origin", description: "Choose a sorcerous origin, which describes the source of your innate magical power. Your choice grants you features when you choose it at 1st level and again at 6th, 14th, and 18th level.", level_requirement: 1)
Feature.create(classifiable_id: 10, classifiable_type: "Klass", name: "Font of Magic", description: "At 2nd level, you tap into a deep wellspring of magic within yourself. This wellspring is represented by sorcery points, which allow you to create a variety of magical effects.
Sorcery Points
You have 2 sorcery points, and you gain more as you reach higher levels, as shown in the Sorcery Points column of Table: The Sorcerer. You can never have more sorcery points than shown on the table for your level. You regain all spent sorcery points when you finish a long rest.
Flexible Casting
You can use your sorcery points to gain additional spell slots, or sacrifice spell slots to gain additional sorcery points. You learn other ways to use your sorcery points as you reach higher levels.
Creating Spell Slots. You can transform unexpended sorcery points into one spell slot as a bonus action on your turn. The Creating Spell Slots table shows the cost of creating a spell slot of a given level. You can create spell slots no higher in level than 5th. Any spell slot you create with this feature vanishes when you finish a long rest.
Converting a Spell Slot to Sorcery Points. As a bonus action on your turn, you can expend one spell slot and gain a number of sorcery points equal to the slot’s level.", level_requirement: 2)
Feature.create(classifiable_id: 10, classifiable_type: "Klass", name: "Metamagic", description: "At 3rd level, you gain the ability to twist your spells to suit your needs. You gain two of the following Metamagic options of your choice. You gain another one at 10th and 17th level. You can use only one Metamagic option on a spell when you cast it, unless otherwise noted.", level_requirement: 3)
Feature.create(classifiable_id: 10, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 10, classifiable_type: "Klass", name: "Sorcerous Restoration", description: "At 20th level, you regain 4 expended sorcery points whenever you finish a short rest.", level_requirement: 4)


# Warlock Features

Feature.create(classifiable_id: 11, classifiable_type: "Klass", name: "Armor Proficiencies", description: "Light armor", level_requirement: 1)
Feature.create(classifiable_id: 11, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Simple weapons", level_requirement: 1)
Feature.create(classifiable_id: 11, classifiable_type: "Klass", name: "Otherwordly Patron", description: "At 1st level, you have struck a bargain with an otherworldly being of your choice. Your choice grants you features at 1st level and again at 6th, 10th, and 14th level.", level_requirement: 1)
Feature.create(classifiable_id: 11, classifiable_type: "Klass", name: "Pact Magic", description: "Your arcane research and the magic bestowed on you by your patron have given you facility with spells.", level_requirement: 1)
Feature.create(classifiable_id: 11, classifiable_type: "Klass", name: "Eldritch Invocations", description: "In your study of occult lore, you have unearthed eldritch invocations, fragments of forbidden knowledge that imbue you with an abiding magical ability. At 2nd level, you gain two eldritch invocations of your choice. Your invocation options are detailed at the end of the class description. When you gain certain warlock levels, you gain additional invocations of your choice, as shown in the Invocations Known column of the Warlock table. Additionally, when you gain a level in this class, you can choose one of the invocations you know and replace it with another invocation that you could learn at that level.", level_requirement: 2)
Feature.create(classifiable_id: 11, classifiable_type: "Klass", name: "Pact Boon", description: "At 3rd level, your otherworldly patron bestows a gift upon you for your loyal service.
Pact of the Chain
You learn the find familiar spell and can cast it as a ritual. The spell doesn’t count against your number of spells known. When you cast the spell, you can choose one of the normal forms for your familiar or one of the following special forms: imp, pseudodragon, quasit, or sprite. Additionally, when you take the Attack action, you can forgo one of your own attacks to allow your familiar to make one attack of its own with its reaction.
Pact of the Blade
You can use your action to create a pact weapon in your empty hand. You can choose the form that this melee weapon takes each time you create it. You are proficient with it while you wield it. This weapon counts as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage. Your pact weapon disappears if it is more than 5 feet away from you for 1 minute or more. It also disappears if you use this feature again, if you dismiss the weapon (no action required), or if you die. You can transform one magic weapon into your pact weapon by performing a special ritual while you hold the weapon. You perform the ritual over the course of 1 hour, which can be done during a short rest. You can then dismiss the weapon, shunting it into an extradimensional space, and it appears whenever you create your pact weapon thereafter. You can’t affect an artifact or a sentient weapon in this way. The weapon ceases being your pact weapon if you die, if you perform the 1-hour ritual on a different weapon, or if you use a 1-hour ritual to break your bond to it. The weapon appears at your feet if it is in the extradimensional space when the bond breaks.
Pact of the Tome
Your patron gives you a grimoire called a Book of Shadows. When you gain this feature, choose three cantrips from any class’s spell list (the three needn’t be from the same list). While the book is on your person, you can cast those cantrips at will. They don’t count against your number of cantrips known. If they don’t appear on the warlock spell list, they are nonetheless warlock spells for you. If you lose your Book of Shadows, you can perform a 1-hour ceremony to receive a replacement from your patron. This ceremony can be performed during a short or long rest, and it destroys the previous book. The book turns to ash when you die.", level_requirement: 3)
Feature.create(classifiable_id: 11, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 11, classifiable_type: "Klass", name: "Mystic Arcanum", description: "At 11th level, your patron bestows upon you a magical secret called an arcanum. Choose one 6th- level spell from the warlock spell list as this arcanum. You can cast your arcanum spell once without expending a spell slot. You must finish a long rest before you can do so again. At higher levels, you gain more warlock spells of your choice that can be cast in this way: one 7th- level spell at 13th level, one 8th-level spell at 15th level, and one 9th-level spell at 17th level. You regain all uses of your Mystic Arcanum when you finish a long rest.", level_requirement: 11)
Feature.create(classifiable_id: 11, classifiable_type: "Klass", name: "Eldritch Master", description: "At 20th level, you can draw on your inner reserve of mystical power while entreating your patron to regain expended spell slots. You can spend 1 minute entreating your patron for aid to regain all your expended spell slots from your Pact Magic feature. Once you regain spell slots with this feature, you must finish a long rest before you can do so again.", level_requirement: 20)


# Wizard Features

Feature.create(classifiable_id: 12, classifiable_type: "Klass", name: "Weapon Proficiencies", description: "Daggers, darts, slings, quarterstaffs, light crossbows", level_requirement: 1)
Feature.create(classifiable_id: 12, classifiable_type: "Klass", name: "Spellcasting", description: "As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power.", level_requirement: 1)
Feature.create(classifiable_id: 12, classifiable_type: "Klass", name: "Arcane Recovery", description: "You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher. For example, if you’re a 4th-level wizard, you can recover up to two levels worth of spell slots. You can recover either a 2nd-level spell slot or two 1st-level spell slots.", level_requirement: 1)
Feature.create(classifiable_id: 12, classifiable_type: "Klass", name: "Arcane Tradition", description: "When you reach 2nd level, you choose an arcane tradition, shaping your practice of magic through one of eight schools: Abjuration, Conjuration, Divination, Enchantment, Evocation, Illusion, Necromancy, or Transmutation, all detailed at the end of the class description. Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level.", level_requirement: 2)
Feature.create(classifiable_id: 12, classifiable_type: "Klass", name: "Ability Score Improvement", description: "When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.", level_requirement: 4)
Feature.create(classifiable_id: 12, classifiable_type: "Klass", name: "Spell Mastery", description: "At 18th level, you have achieved such mastery over certain spells that you can cast them at will. Choose a 1st-level wizard spell and a 2nd-level wizard spell that are in your spellbook. You can cast those spells at their lowest level without expending a spell slot when you have them prepared. If you want to cast either spell at a higher level, you must expend a spell slot as normal. By spending 8 hours in study, you can exchange one or both of the spells you chose for different spells of the same levels.", level_requirement: 18)
Feature.create(classifiable_id: 12, classifiable_type: "Klass", name: "Signature Spells", description: "When you reach 20th level, you gain mastery over two powerful spells and can cast them with little effort. Choose two 3rd-level wizard spells in your spellbook as your signature spells. You always have these spells prepared, they don’t count against the number of spells you have prepared, and you can cast each of them once at 3rd level without expending a spell slot. When you do so, you can’t do so again until you finish a short or long rest. If you want to cast either spell at a higher level, you must expend a spell slot as normal.", level_requirement: 20)


#THIS IS THE LAST LINE