Skill.create(name: "Acrobatics", ability: "dexterity")
Skill.create(name: "Animal Handling", ability: "wisdom")
Skill.create(name: "Arcana", ability: "intelligence")
Skill.create(name: "Athletics", ability: "strength")
Skill.create(name: "Deception", ability: "charisma")
Skill.create(name: "History", ability: "intelligence")
Skill.create(name: "Insight", ability: "wisdom")
Skill.create(name: "Intimidation", ability: "charisma")
Skill.create(name: "Investigation", ability: "intelligence")
Skill.create(name: "Medicine", ability: "wisdom")
Skill.create(name: "Nature", ability: "intelligence")
Skill.create(name: "Perception", ability: "wisdom")
Skill.create(name: "Performance", ability: "charisma")
Skill.create(name: "Persuasion", ability: "charisma")
Skill.create(name: "Religion", ability: "intelligence")
Skill.create(name: "Sleight of Hand", ability: "dexterity")
Skill.create(name: "Stealth", ability: "dexterity")
Skill.create(name: "Survival", ability: "wisdom")