Subrace.create(name: "Hill Dwarf", race_id: 1)
Subrace.create(name: "Mountain Dwarf", race_id: 1)
Subrace.create(name: "High Elf", race_id: 2)
Subrace.create(name: "Wood Elf", race_id: 2)
Subrace.create(name: "Dark Elf (Drow)", race_id: 2)
Subrace.create(name: "Lightfoot", race_id: 3)
Subrace.create(name: "Stout", race_id: 3)
Subrace.create(name: "Forest Gnome", race_id: 6)
Subrace.create(name: "Rock Gnome", race_id: 6)